version: '3.8'

services:
    redis:
        image: redis:alpine
        container_name: lks_redis
        ports:
            - 6379:6379
        networks: 
            - lks_network
        command: redis-server --requirepass br4v0Sth!ingS!@#

networks: 
    lks_network:
        name: lks_network