version: '3.8'

services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile
        image: betuah/sthing_server:release
        container_name: sthing_server
        env_file: dev.env
        volumes: 
            - ./public:/usr/src/app/public
            - ./ssl:/usr/src/app/ssl
        ports:
            - 8000:8000
        command: npm run start